name: translator_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  permission_handler: ^12.0.0+1

  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  google_sign_in: ^6.2.1
  cloud_firestore: ^4.14.0
  shared_preferences: ^2.2.2
  http: ^1.1.0
  path_provider: ^2.1.2
  flutter_svg: ^2.0.7
  flutter_local_notifications: ^19.2.1
  flutter_local_notifications_linux: ^6.0.0
  connectivity_plus: ^4.0.0
  intl: ^0.18.1
  rxdart: ^0.28.0

  google_api_availability: ^5.0.1

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  fonts:

    - family: MediaSans
      fonts:
        - asset: assets/fonts/mediasans-bold-TRIAL-BF63c7546b153ef.otf
        - asset: assets/fonts/mediasans-bold-TRIAL-BF63c7546b153ef.otf

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf

  assets:
    - assets/backgrounds/waves.svg
    - assets/flags/
