// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNcssdYilqCIhvPoL2XO0bNxLGqbBmY-E',
    appId: '1:222989533931:web:58ed94efb4b9a7fa77b4ae',
    messagingSenderId: '222989533931',
    projectId: 'calculator-bec09',
    authDomain: 'calculator-bec09.firebaseapp.com',
    storageBucket: 'calculator-bec09.firebasestorage.app',
    measurementId: 'G-90N8R32KGJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChYIshOxlMCwHzVxIQs_1aZ9H13u8eYQs',
    appId: '1:222989533931:android:b15e421221053c3377b4ae',
    messagingSenderId: '222989533931',
    projectId: 'calculator-bec09',
    storageBucket: 'calculator-bec09.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_J6rhRII3eliFN1bxOrqXd7hIlKhfByk',
    appId: '1:222989533931:ios:2cbcdeaefc2df2d177b4ae',
    messagingSenderId: '222989533931',
    projectId: 'calculator-bec09',
    storageBucket: 'calculator-bec09.firebasestorage.app',
    androidClientId: '222989533931-v0s4l1shueliil2tgkp6o7mnibt54n1u.apps.googleusercontent.com',
    iosClientId: '222989533931-a298p93tn9gk0i4hvogb4265fgdj20nv.apps.googleusercontent.com',
    iosBundleId: 'com.example.translatorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_J6rhRII3eliFN1bxOrqXd7hIlKhfByk',
    appId: '1:222989533931:ios:2cbcdeaefc2df2d177b4ae',
    messagingSenderId: '222989533931',
    projectId: 'calculator-bec09',
    storageBucket: 'calculator-bec09.firebasestorage.app',
    androidClientId: '222989533931-v0s4l1shueliil2tgkp6o7mnibt54n1u.apps.googleusercontent.com',
    iosClientId: '222989533931-a298p93tn9gk0i4hvogb4265fgdj20nv.apps.googleusercontent.com',
    iosBundleId: 'com.example.translatorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNcssdYilqCIhvPoL2XO0bNxLGqbBmY-E',
    appId: '1:222989533931:web:5216f3d4c175a6a277b4ae',
    messagingSenderId: '222989533931',
    projectId: 'calculator-bec09',
    authDomain: 'calculator-bec09.firebaseapp.com',
    storageBucket: 'calculator-bec09.firebasestorage.app',
    measurementId: 'G-7XTKSRMQBH',
  );
}
